services:
  backend:
    image: tcdswenggroup18/codecraft:backend-deployment
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - ./backend/.env

  frontend:
    image: tcdswenggroup18/codecraft:frontend-deployment
    build:
      context: .
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge