name: Docker Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    name: Build and Push Docker Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: docker

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tcdswenggroup18/codecraft:frontend-1
          
      - name: Build and Push frontend
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: tcdswenggroup18/codecraft:frontend-1
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_backend:
    name: Build and Push Docker Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: docker

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tcdswenggroup18/codecraft:backend-1
          
      - name: Build and Push frontend
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: tcdswenggroup18/codecraft:backend-1
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
