name: Frontend Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: frontend

    - name: Install Node.js dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install npm dependencies
      run: npm install

    - name: Run tests
      run: |
       cd frontend
       npm test
       a