name: Unit Testing

on:
  pull_request:
    branches:
      - main

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
  HUGGINGFACE_TOKEN: ${{ HUGGINGFACE_KEY }}

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: backend

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Run codecraft.py
      run: python backend/codecraft.py

    - name: Run unit tests
      run: |
        python -m unittest backend.junittest
