name: Unit Testing

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: backend

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

